#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

echo "Cleaning..."

rm -rfv processor*
rm -rfv postProcessing
rm -rfv 0
# Create an empty .foam file for ParaView
# Note: ".foam" triggers the native OpenFOAM reader of ParaView.
# Change to ".OpenFOAM" to use the OpenFOAM reader provided with OpenFOAM.
# touch ${Participant1}.foam

# Remove the log files
rm -fv log.*
rm -fv precice*.log
rm -rfv precice-profiling
