name: Build
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-22.04
    container: tumi5/latex
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Prepare system
      run: |
        apt-get update && apt-get install -y poppler-utils
    - name: Build
      run: |
        cd fsi-workflow && make
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: fsi-workflow/fsi-workflow-tasks.pdf
        if-no-files-found: error
