name: Build
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-22.04
    container: tumi5/latex
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Prepare system
      run: |
        apt-get update && apt-get install -y poppler-utils
        pip install pandoc-fignos
    - name: Build
      run: |
        cd fsi-workflow && make
    - name: Upload tasks
      uses: actions/upload-artifact@v4
      with:
        name: fsi-workflow-tasks
        path: fsi-workflow/fsi-workflow-tasks.pdf
        if-no-files-found: error
    - name: Upload fsi-workflow
      uses: actions/upload-artifact@v4
      with:
        name: fsi-workflow
        path: fsi-workflow
        if-no-files-found: error
