name: Build
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    container: tumi5/latex
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Prepare system
      run: |
        apt-get update && apt-get install -y python3-venv
        python3 -m venv .venv && . .venv/bin/activate
        echo PATH=$PATH >> $GITHUB_ENV
        pip install poppler-utils
        # Workaround for https://github.com/tomduck/pandoc-xnos/pull/29
        pip install --force-reinstall git+https://github.com/nandokawka/pandoc-xnos@284474574f51888be75603e7d1df667a0890504d#egg=pandoc-xnos
    - name: Build
      run: |
        cd fsi-workflow && make
    - name: Upload tasks
      uses: actions/upload-artifact@v4
      with:
        name: precice-course-fsi-workflow-tasks
        path: fsi-workflow/precice-course-fsi-workflow-tasks.pdf
        if-no-files-found: error
    - name: Prepare src archive
      run: |
        cd fsi-workflow && make clean && cd ..
        tar -czf precice-course-fsi-workflow-src.tar.gz fsi-workflow
    - name: Upload src archive
      uses: actions/upload-artifact@v4
      with:
        name: precice-course-fsi-workflow-src
        path: precice-course-fsi-workflow-src.tar.gz
        if-no-files-found: error
